spring:
  application:
    name: config-client
  rabbitmq:
    host: localhost
    port: 5672
#    username: guest
#    password: guest
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-server
server:
  port: 8881
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/